version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo "Install phase"
      # Install serverless
      - npm install -g serverless -y
      - echo "Installing python"
      # Install python
      - apt install software-properties-common -y
#      - add-apt-repository ppa:jonathonf/python-3.6 -y
#      - apt update
#      - apt install python3.6 -y
#      - apt install python3.6-dev -y
      # Install pip
#      - wget https://bootstrap.pypa.io/get-pip.py
#      - python3.6 get-pip.py
  pre_build:
    commands:
      - echo "Pre Build phase skipped"
  build:
    commands:
      - echo "Build phase"
      - npm install
  post_build:
    commands:
      - sls deploy --stage ${STAGE} --no-color