version: "3"
services:
    db:
      container_name: db
      image: amazon/dynamodb-local
      ports:
        - "8000:8000"
    migration:
      container_name: migration
      build:
        context: ./
        dockerfile: Dockerfile.migrate
      depends_on:
        - db
    app:
        container_name: app
        build:
          context: ./
          dockerfile: Dockerfile.app
        restart: always
        ports:
          - "5000:5000"
        depends_on:
          - db
          - migration

